### ISSUE TITLE
Overfitting issue about the fine-tuned GLM

### ISSUE THREAD

**Issue by yuezhao238** [boluoweifenda/werewolf#6]
Hi, thanks for this great work!

Did you analyse the behavior of finetuned model? I found the GLM show overfitting behavior after finetuning. Will you release your model weights?

Thanks for your precious time!

**Comment by boluoweifenda** [comment]
Yes, we also notice the overfitting in speech generation.
A method not mentioned in the paper is to rewrite speeches by other LLMs, for example, we used Baichuan2 to augment speeches in the dataset. But it introduces the bias of LLMs and promptings.
You can have a try on more recent models such as llama3, I think it would be much better.

**Comment by yuezhao238** [comment]
Thanks for your reply!
